#!/usr/bin/env python3
"""Rewrite the README's generated table from the client's ONE table registry
(``geodb.client.TABLES``) — so the README cannot list a method, path or export
model the client does not have.

    python scripts/gen_readme.py           # rewrite the marked region
    python scripts/gen_readme.py --check   # exit 1 when it is stale
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN:tables (generated by scripts/gen_readme.py from geodb.client.TABLES) -->"
END = "<!-- END:tables -->"


def render():
    from geodb.client import TABLES
    lines = ["| Records lane | `export()` model | Sets | What it is |", "|---|---|---|---|"]
    for name, path, exports, sets, what in TABLES:
        export = ", ".join(f"`{e}`" for e in exports) or "—"
        lines.append(f"| `gx.{name}(project=…)` | {export} | {'`set=`' if sets else '—'} | "
                     f"{what} (`{path}`) |")
    return "\n".join([BEGIN, *lines, END])


def _current():
    text = README.read_text(encoding="utf-8")
    a, b = text.index(BEGIN), text.index(END) + len(END)
    return text, a, b


def stale():
    text, a, b = _current()
    return "" if text[a:b] == render() else "the tables region differs from TABLES"


def main(argv):
    if "--check" in argv:
        problem = stale()
        print(problem or "[OK] README tables match geodb.client.TABLES")
        return 1 if problem else 0
    text, a, b = _current()
    README.write_text(text[:a] + render() + text[b:], encoding="utf-8")
    print("wrote README.md tables")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
